name: Build and deploy JAR app to Azure Web App - expense-tracker-api-bophelo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Build backend with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: backend/target/*.jar

 deploy:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24942C6E41024CEE948121E9294A0122 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0FAD0BF321D4ECA857F4D54CA2F9C29 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BB702DCEA82C42D7849EA72890B9DDCC }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: expense-tracker-api-bophelo
          slot-name: Production
          package: java-app/*.jar
