name: Build and deploy JAR app to Azure Web App - stuent-expense-tracker-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E62C853384AA459CA1CBD8409FC7C4E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32C5B517AD0A481399FEFB99FDE1A123 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_43CAF61FC8E34188A0B4D7CB5BA0CDD4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stuent-expense-tracker-api'
          slot-name: 'Production'
          package: java-app/*.jar
